.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" supervise-ldirectord-config.8                             March 2003
.\" Horms                                             horms@verge.net.au
.\"
.\" ldirectord
.\" Linux Director Daemon
.\" (C) 2003 Jacob Rief <jacob.rief@tiscover.com> and Horms <horms@verge.net.au>
.\" 
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of the
.\" License, or (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307  USA
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH SUPERVISE-LDIRECTORD-CONFIG 8 "24th March 2003"
.SH NAME
supervise-ldirectord-config \- daemontools script for ldirectord
.SH SYNOPSIS
\fBsupervise-ldirectord-config\fP ldirectord_configuration_file
.SH DESCRIPTION
This script puts ldirectord under
control of daemontools. This is safer than System V
init-script since ldirectord is restarted by supervise
after a crash. 

For this to work correctly the supervise directive
must be present in the ldirectord_configuration_file.
This causes ldirectord to remain in the forground
and send logs to stdout so they can be handled
by daemontools.
.SH SEE ALSO
ldirectord(8), http://cr.yp.to/daemontools.html
.SH AUTHORS
Jacob Rief <jacob.rief@tiscover.com>
.br
Horms <horms@verge.net.au>
