.TH HB_ADDNODE 1 "21st November 2005" 
.SH NAME
hb_addnode \-  hb_addnode is a simple linux-ha shell script. It sends a message to the cluster to add new nodes.
.SH SYNOPSIS
.B hb_addnode
.nh
.RI "\fB<node1>\fP \fB[node2]\fP \fB[node3]\fP \fB...\fP"
.P
.SH DESCRIPTION
The full path is usually /usr/lib/heartbeat/hb_addnode. 
To get a list of the options, issue the command, 
\fB "/usr/lib/heartbeat/hb_addnode --help" \fP 

If there is any node in the arguments has already been in the cluster, the command will fail and
no node will be added.


.SH SEE ALSO
hb_delnode(1), heartbeat(8), cl_status(1)

.SH AUTHORS

linux-ha -- Alan Robertson
.UR mailto:alanr@unix.sh
<alanr@unix.sh>
.UE
\fIet al\fP.

man page -- Guochun Shi
.UR mailto:gshi@ncsa.uiuc.edu
<gshi@ncsa.uiuc.edu>
.UE

