.TH HB_DELNODE 1 "21st November 2005" 
.SH NAME
hb_delnode \-  hb_delnode is a simple linux-ha shell script. It sends a message to the cluster to delete nodes.
.SH SYNOPSIS
.B hb_delnode
.nh
.RI "\fB<node1>\fP \fB[node2]\fP \fB[node3]\fP \fB...\fP"
.P
.SH DESCRIPTION
The full path is usually /usr/lib/heartbeat/hb_delnode. 
To get a list of the options, issue the command, 
\fB "/usr/lib/heartbeat/hb_delnode --help" \fP 

If there is any node in the arguments is not in the cluster, the command will fail and
no node will be deleted.


.SH SEE ALSO
hb_addnode(1), heartbeat(8), cl_status(1)

.SH AUTHORS

linux-ha -- Alan Robertson
.UR mailto:alanr@unix.sh
<alanr@unix.sh>
.UE
\fIet al\fP.

man page -- Guochun Shi
.UR mailto:gshi@ncsa.uiuc.edu
<gshi@ncsa.uiuc.edu>
.UE

