.TH HEARTBEAT 8 "29 May 2003"
.SH NAME
heartbeat \- Heartbeat subsystem for High-Availability Linux
.SH SYNOPSIS
.B heartbeat
.nh
.RI "[ -dkrRsv ] [-C Current-resource-state ]"
.br
.RI "-C only valid with -R"
.br
.RI "-r is mutually exclusive with -R"
.SH DESCRIPTION
\fBheartbeat\fP is a basic heartbeat subsystem for Linux-HA.
It will run scripts at initialisation, and when machines go up or down.
This version will also perform IP address takeover using gratuitous ARPs.
It works correctly for a 2-node configuration, and is extensible to larger
configurations.
.PP
It implements the following kinds of heartbeats:
   * Bidirectional Serial Rings ("raw" serial ports)
   * UDP/IP broadcast (ethernet, etc.)
   * UDP/IP multicast (ethernet, etc.)
   * special "ping" heartbeats for routers, etc.
.PP
Comprehensive documentation on the configuration and running of
\fBheartbeat\fP can is supplied in HTML format with the distribution 
of the code. If this documentation is not installed on your system
it can be found, with the latest distribution of heartbeat
on http://www.linux-ha.org/
.SH OPTIONS
.TP
\fB-d\fP
increment debugging level
.TP
\fB-r\fP
restart heartbeat
.TP
\fB-k\fP
kill (stop) heartbeat
.TP
\fB-s\fP
report heartbeat status
.TP
\fB-R\fP
Heartbeat restart exec flag (internal use only)
.TP
\fB-C\fP
Heartbeat current resource state for restart (internal use only)
.PP
Note that most of these options are used for supporting the heartbeat
\fIinit script\fP, which provides the conventional start,
stop, status and restart options (among others).

.SH AUTHORS
.nf
heartbeat - Alan Robertson <alanr@unix.sh> et al.
man page - Juan Pedro Paredes Caballero <juampe@retemail.es>
           Horms <horms@vergenet.net>
.fi

