/* This file was generated by mib2c and is intended for use as a mib module
  for the ucd-snmp snmpd agent. */


#ifndef _MIBGROUP_HAIFTABLE_H
#define _MIBGROUP_HAIFTABLE_H


/* we may use header_generic and header_simple_table from the util_funcs module */


config_require(util_funcs)


/* function prototypes */


void   init_HAIFTable(void);
FindVarMethod var_HAIFTable;
FindVarMethod var_HAIFTable;

int header_ifInfo(struct variable * vp,
			    oid             * name,
			    size_t          * length,
			    int               exact,
			    size_t          * var_len,
			    WriteMethod     * *write_method,
			    size_t          * index);

#endif /* _MIBGROUP_HAIFTABLE_H */
