/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef LHACLUSTERINFO_H
#define LHACLUSTERINFO_H

/* function declarations */
void init_LHAClusterInfo(void);
Netsnmp_Node_Handler handle_LHALiveNodeCount;
Netsnmp_Node_Handler handle_LHATotalNodeCount;

#endif /* LHACLUSTERINFO_H */
