/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef LHAHEARTBEATCONFIGINFO_H
#define LHAHEARTBEATCONFIGINFO_H

/* function declarations */
void init_LHAHeartbeatConfigInfo(void);
Netsnmp_Node_Handler handle_LHAHBVersion;
Netsnmp_Node_Handler handle_LHAAPIAuth;
Netsnmp_Node_Handler handle_LHADebugFile;
Netsnmp_Node_Handler handle_LHADebug;
Netsnmp_Node_Handler handle_LHAHOPFudge;
Netsnmp_Node_Handler handle_LHARespawn;
Netsnmp_Node_Handler handle_LHADeadTime;
Netsnmp_Node_Handler handle_LHAInitDead;
Netsnmp_Node_Handler handle_LHAUDPPort;
Netsnmp_Node_Handler handle_LHALogFile;
Netsnmp_Node_Handler handle_LHAStonith;
Netsnmp_Node_Handler handle_LHABaudRate;
Netsnmp_Node_Handler handle_LHNiceFailBack;
Netsnmp_Node_Handler handle_LHARTPriority;
Netsnmp_Node_Handler handle_LHAMsgFmt;
Netsnmp_Node_Handler handle_LHARealTime;
Netsnmp_Node_Handler handle_LHAStonithHost;
Netsnmp_Node_Handler handle_LHANormalPoll;
Netsnmp_Node_Handler handle_LHAGenMethod;
Netsnmp_Node_Handler handle_LHAWarnTime;
Netsnmp_Node_Handler handle_LHADeadPing;
Netsnmp_Node_Handler handle_LHAKeepAlive;
Netsnmp_Node_Handler handle_LHAWatchdogTimer;
Netsnmp_Node_Handler handle_LHALogFacility;
Netsnmp_Node_Handler handle_LHAutoFailBack;

#endif /* LHAHEARTBEATCONFIGINFO_H */
