/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.9 2003/06/04 00:14:41 hardaker Exp $
 */
#ifndef LHAIFTABLE_H
#define LHAIFTABLE_H

/* function declarations */
void init_LHAIFTable(void);
void initialize_table_LHAIFTable(void);
Netsnmp_Node_Handler LHAIFTable_handler;

Netsnmp_First_Data_Point  LHAIFTable_get_first_data_point;
Netsnmp_Next_Data_Point   LHAIFTable_get_next_data_point;

/* column number definitions for table LHAIFTable */
#include "LHAIFTable_columns.h"

/* enum definions */
#include "LHAIFTable_enums.h"

#endif /* LHAIFTABLE_H */
