/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */
#ifndef LHAIFTABLE_COLUMNS_H
#define LHAIFTABLE_COLUMNS_H

/* column number definitions for table LHAIFTable */
       #define COLUMN_LHAIFINDEX		1
       #define COLUMN_LHAIFNAME		2
       #define COLUMN_LHAIFSTATUS		3
#endif /* LHAIFTABLE_COLUMNS_H */
