/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_enums.conf,v 5.2 2003/02/22 04:09:25 hardaker Exp $
 */
#ifndef LHAIFSTATUSTABLE_ENUMS_H
#define LHAIFSTATUSTABLE_ENUMS_H

#endif /* LHAIFSTATUSTABLE_ENUMS_H */
