/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */
#ifndef LHAIFSTATUSTABLE_COLUMNS_H
#define LHAIFSTATUSTABLE_COLUMNS_H

/* column number definitions for table LHAIFStatusTable */
       #define COLUMN_LHAIFINDEX		1
       #define COLUMN_LHAIFNAME		2
       #define COLUMN_LHAIFSTATUS		3
#endif /* LHAIFSTATUSTABLE_COLUMNS_H */
