/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */
#ifndef LHAMEMBERSHIPTABLE_COLUMNS_H
#define LHAMEMBERSHIPTABLE_COLUMNS_H

/* column number definitions for table LHAMembershipTable */
       #define COLUMN_LHAMEMBERINDEX		1
       #define COLUMN_LHAMEMBERNAME		2
       #define COLUMN_LHAMEMBERADDRESS		3
       #define COLUMN_LHAMEMBERCLUSTERNAME		4
       #define COLUMN_LHAMEMBERISMEMBER		5
       #define COLUMN_LHAMEMBERLASTCHANGE		6
       #define COLUMN_LHAMEMBERBOOTTIME		7
#endif /* LHAMEMBERSHIPTABLE_COLUMNS_H */
