/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.9 2003/06/04 00:14:41 hardaker Exp $
 */
#ifndef LHAMEMBERSHIPTABLE_H
#define LHAMEMBERSHIPTABLE_H

/* function declarations */
void init_LHAMembershipTable(void);
void initialize_table_LHAMembershipTable(void);
Netsnmp_Node_Handler LHAMembershipTable_handler;

Netsnmp_First_Data_Point  LHAMembershipTable_get_first_data_point;
Netsnmp_Next_Data_Point   LHAMembershipTable_get_next_data_point;

/* column number definitions for table LHAMembershipTable */
#include "LHAMembershipTable_columns.h"

/* enum definions */
#include "LHAMembershipTable_enums.h"

#endif /* LHAMEMBERSHIPTABLE_H */
