/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_enums.conf,v 5.2 2003/02/22 04:09:25 hardaker Exp $
 */
#ifndef LHAMEMBERSHIPTABLE_ENUMS_H
#define LHAMEMBERSHIPTABLE_ENUMS_H

/* enums for column LHAMemberIsMember */
           #define LHAMEMBERISMEMBER_TRUE		1
           #define LHAMEMBERISMEMBER_FALSE		2

/* enums for column LHAMemberLastChange */
           #define LHAMEMBERLASTCHANGE_UNDEFINED		0
           #define LHAMEMBERLASTCHANGE_NOCHANGE		1
           #define LHAMEMBERLASTCHANGE_JOINED		2
           #define LHAMEMBERLASTCHANGE_LEFT		3

#endif /* LHAMEMBERSHIPTABLE_ENUMS_H */
