/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.9 2003/06/04 00:14:41 hardaker Exp $
 */
#ifndef LHANODETABLE_H
#define LHANODETABLE_H

/* function declarations */
void init_LHANodeTable(void);
void initialize_table_LHANodeTable(void);
Netsnmp_Node_Handler LHANodeTable_handler;

Netsnmp_First_Data_Point  LHANodeTable_get_first_data_point;
Netsnmp_Next_Data_Point   LHANodeTable_get_next_data_point;

/* column number definitions for table LHANodeTable */
#include "LHANodeTable_columns.h"

/* enum definions */
#include "LHANodeTable_enums.h"

#endif /* LHANODETABLE_H */
