/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */
#ifndef LHANODETABLE_COLUMNS_H
#define LHANODETABLE_COLUMNS_H

/* column number definitions for table LHANodeTable */
       #define COLUMN_LHANODEINDEX		1
       #define COLUMN_LHANODENAME		2
       #define COLUMN_LHANODETYPE		3
       #define COLUMN_LHANODESTATUS		4
       #define COLUMN_LHANODEUUID		5
       #define COLUMN_LHANODEIFCOUNT		6
#endif /* LHANODETABLE_COLUMNS_H */
