/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.9 2003/06/04 00:14:41 hardaker Exp $
 */
#ifndef LHARESOURCEGROUPTABLE_H
#define LHARESOURCEGROUPTABLE_H

/* function declarations */
void init_LHAResourceGroupTable(void);
void initialize_table_LHAResourceGroupTable(void);
Netsnmp_Node_Handler LHAResourceGroupTable_handler;

Netsnmp_First_Data_Point  LHAResourceGroupTable_get_first_data_point;
Netsnmp_Next_Data_Point   LHAResourceGroupTable_get_next_data_point;

/* column number definitions for table LHAResourceGroupTable */
#include "LHAResourceGroupTable_columns.h"

/* enum definions */
#include "LHAResourceGroupTable_enums.h"

#endif /* LHARESOURCEGROUPTABLE_H */
