/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf,v 5.2.2.1 2004/04/15 12:29:06 dts12 Exp $
 */
#ifndef LHARESOURCESTATUSUPDATE_H
#define LHARESOURCESTATUSUPDATE_H


/*
 * function declarations 
 */
int             send_LHAResourceStatusUpdate_trap(struct hb_rsinfov2 *resource);

#endif                          /* LHARESOURCESTATUSUPDATE_H */
