/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */
#ifndef LHARESOURCEGROUPTABLE_COLUMNS_H
#define LHARESOURCEGROUPTABLE_COLUMNS_H

/* column number definitions for table LHAResourceGroupTable */
       #define COLUMN_LHARESOURCEGROUPINDEX		1
       #define COLUMN_LHARESOURCEGROUPMASTER		2
       #define COLUMN_LHARESOURCEGROUPRESOURCES		3
       #define COLUMN_LHARESOURCEGROUPSTATUS		4
#endif /* LHARESOURCEGROUPTABLE_COLUMNS_H */
