/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.9 2003/06/04 00:14:41 hardaker Exp $
 */
#ifndef LHARESOURCETABLE_H
#define LHARESOURCETABLE_H

/*
 * function declarations 
 */
void            init_LHAResourceTable(void);
void            initialize_table_LHAResourceTable(void);
Netsnmp_Node_Handler LHAResourceTable_handler;

Netsnmp_First_Data_Point LHAResourceTable_get_first_data_point;
Netsnmp_Next_Data_Point LHAResourceTable_get_next_data_point;

/*
 * column number definitions for table LHAResourceTable 
 */
#include "LHAResourceTable_columns.h"

/*
 * enum definions 
 */
#include "LHAResourceTable_enums.h"

#endif                          /* LHARESOURCETABLE_H */
