/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */
#ifndef LHARESOURCETABLE_COLUMNS_H
#define LHARESOURCETABLE_COLUMNS_H

/*
 * column number definitions for table LHAResourceTable 
 */
#define COLUMN_LHARESOURCEINDEX		1
#define COLUMN_LHARESOURCENAME		2
#define COLUMN_LHARESOURCETYPE		3
#define COLUMN_LHARESOURCENODE		4
#define COLUMN_LHARESOURCESTATUS		5
#define COLUMN_LHARESOURCEISMANAGED           6
#define COLUMN_LHARESOURCEFAILCOUNT           7
#define COLUMN_LHARESOURCEPARENT              8
#endif                          /* LHARESOURCETABLE_COLUMNS_H */
