/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_enums.conf,v 5.2 2003/02/22 04:09:25 hardaker Exp $
 */
#ifndef LHARESOURCETABLE_ENUMS_H
#define LHARESOURCETABLE_ENUMS_H

/*
 * enums for column LHAResourceType 
 */
#define LHARESOURCETYPE_UNKNOWN		0
#define LHARESOURCETYPE_PRIMITIVE		1
#define LHARESOURCETYPE_GROUP		2
#define LHARESOURCETYPE_CLONE		3
#define LHARESOURCETYPE_MASTERSLAVE		4

/*
 * enums for column LHAResourceStatus 
 */
#define LHARESOURCESTATUS_UNKNOWN		0
#define LHARESOURCESTATUS_STOPPED		1
#define LHARESOURCESTATUS_STARTED		2
#define LHARESOURCESTATUS_SLAVE		3
#define LHARESOURCESTATUS_MASTER		4

/*
 * enums for column LHAResourceIsManaged
 */
#define LHARESOURCEISMANAGED_UNMANAGED                0
#define LHARESOURCEISMANAGED_MANAGED          1

#endif                          /* LHARESOURCETABLE_ENUMS_H */
