/* This file was generated by mib2c and is intended for use as a mib module
  for the ucd-snmp snmpd agent. */


#ifndef _MIBGROUP_NODETABLE_H
#define _MIBGROUP_NODETABLE_H


/* we may use header_generic and header_simple_table from the util_funcs module */


config_require(util_funcs)


/* function prototypes */


void   init_NodeTable(void);
FindVarMethod var_NodeTable;
FindVarMethod var_NodeTable;





#endif /* _MIBGROUP_NODETABLE_H */
