<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="23" operation="start" operation_key="p_dummy2_start_0" on_node="hpn08" on_node_uuid="hpn08">
        <primitive id="p_dummy2" long-id="p_dummy2" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="10" operation="o_dummy-2-start-begin" operation_key="o_dummy-2-start-begin"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="24" operation="start" operation_key="p_dummy4_start_0" on_node="hpn07" on_node_uuid="hpn07">
        <primitive id="p_dummy4" long-id="p_dummy4" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="14" operation="o_dummy-3-start-begin" operation_key="o_dummy-3-start-begin"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="25" operation="start" operation_key="p_dummy3_start_0" on_node="hpn08" on_node_uuid="hpn08">
        <primitive id="p_dummy3" long-id="p_dummy3" class="ocf" provider="pacemaker" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="10" operation="o_dummy-2-start-begin" operation_key="o_dummy-2-start-begin"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="5" operation="o_dummy-1-promote-end" operation_key="o_dummy-1-promote-end">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="4">
    <action_set>
      <pseudo_event id="9" operation="o_dummy-2-start-end" operation_key="o_dummy-2-start-end">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="23" operation="start" operation_key="p_dummy2_start_0" on_node="hpn08" on_node_uuid="hpn08"/>
      </trigger>
      <trigger>
        <rsc_op id="25" operation="start" operation_key="p_dummy3_start_0" on_node="hpn08" on_node_uuid="hpn08"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="10" operation="o_dummy-2-start-begin" operation_key="o_dummy-2-start-begin">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="5" operation="o_dummy-1-promote-end" operation_key="o_dummy-1-promote-end"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <pseudo_event id="13" operation="o_dummy-3-start-end" operation_key="o_dummy-3-start-end">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="24" operation="start" operation_key="p_dummy4_start_0" on_node="hpn07" on_node_uuid="hpn07"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="14" operation="o_dummy-3-start-begin" operation_key="o_dummy-3-start-begin">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="9" operation="o_dummy-2-start-end" operation_key="o_dummy-2-start-end"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

