<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="8" transition_id="0">
  <synapse id="0">
    <action_set>
      <pseudo_event id="13" operation="start" operation_key="base-group:0_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="33" operation="start" operation_key="base-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="10" operation="start" operation_key="o2cb:0_start_0" on_node="hex-0" on_node_uuid="hex-0">
        <primitive id="o2cb:0" long-id="base-clone:base-group:0:o2cb:0" class="ocf" provider="ocfs2" type="o2cb"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="base-group:0_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="11" operation="start" operation_key="clvm:0_start_0" on_node="hex-0" on_node_uuid="hex-0">
        <primitive id="clvm:0" long-id="base-clone:base-group:0:clvm:0" class="ocf" provider="lvm2" type="clvmd"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" daemon_timeout="30"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="10" operation="start" operation_key="o2cb:0_start_0" on_node="hex-0" on_node_uuid="hex-0"/>
      </trigger>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="base-group:0_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <rsc_op id="12" operation="start" operation_key="cmirrord:0_start_0" on_node="hex-0" on_node_uuid="hex-0">
        <primitive id="cmirrord:0" long-id="base-clone:base-group:0:cmirrord:0" class="ocf" provider="lvm2" type="cmirrord"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" daemon_timeout="60"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="11" operation="start" operation_key="clvm:0_start_0" on_node="hex-0" on_node_uuid="hex-0"/>
      </trigger>
      <trigger>
        <pseudo_event id="13" operation="start" operation_key="base-group:0_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="4">
    <action_set>
      <rsc_op id="6" operation="monitor" operation_key="vg1:0_monitor_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="vg1:0" long-id="base-clone:base-group:0:vg1:0" class="ocf" provider="heartbeat" type="LVM"/>
        <attributes CRM_meta_clone="0" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_op_target_rc="7" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" volgrpname="cluster-vg"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="5">
    <action_set>
      <pseudo_event id="21" operation="start" operation_key="base-group:1_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="24" operation="stopped" operation_key="base-group:1_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="33" operation="start" operation_key="base-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="6">
    <action_set>
      <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="35" operation="stop" operation_key="base-clone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="7">
    <action_set>
      <pseudo_event id="24" operation="stopped" operation_key="base-group:1_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="54" operation="stop" operation_key="dlm:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="stop" operation_key="o2cb:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="56" operation="stop" operation_key="clvm:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="cmirrord:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="58" operation="stop" operation_key="vg1:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="60" operation="stop" operation_key="ocfs2-1:1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="8">
    <action_set>
      <rsc_op id="17" operation="start" operation_key="dlm:1_start_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="dlm:1" long-id="base-clone:base-group:1:dlm:1" class="ocf" provider="pacemaker" type="controld"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="21" operation="start" operation_key="base-group:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="9">
    <action_set>
      <pseudo_event id="54" operation="stop" operation_key="dlm:1_stop_0">
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="stop" operation_key="o2cb:1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="10">
    <action_set>
      <rsc_op id="18" operation="start" operation_key="o2cb:1_start_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="o2cb:1" long-id="base-clone:base-group:1:o2cb:1" class="ocf" provider="ocfs2" type="o2cb"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="17" operation="start" operation_key="dlm:1_start_0" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
      <trigger>
        <pseudo_event id="21" operation="start" operation_key="base-group:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="11">
    <action_set>
      <pseudo_event id="55" operation="stop" operation_key="o2cb:1_stop_0">
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="56" operation="stop" operation_key="clvm:1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="12">
    <action_set>
      <rsc_op id="19" operation="start" operation_key="clvm:1_start_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="clvm:1" long-id="base-clone:base-group:1:clvm:1" class="ocf" provider="lvm2" type="clvmd"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" daemon_timeout="30"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="18" operation="start" operation_key="o2cb:1_start_0" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
      <trigger>
        <pseudo_event id="21" operation="start" operation_key="base-group:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="13">
    <action_set>
      <pseudo_event id="56" operation="stop" operation_key="clvm:1_stop_0">
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" daemon_timeout="30"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="cmirrord:1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="14">
    <action_set>
      <rsc_op id="20" operation="start" operation_key="cmirrord:1_start_0" on_node="hex-9" on_node_uuid="hex-9">
        <primitive id="cmirrord:1" long-id="base-clone:base-group:1:cmirrord:1" class="ocf" provider="lvm2" type="cmirrord"/>
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" daemon_timeout="60"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <rsc_op id="19" operation="start" operation_key="clvm:1_start_0" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
      <trigger>
        <pseudo_event id="21" operation="start" operation_key="base-group:1_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="15">
    <action_set>
      <pseudo_event id="57" operation="stop" operation_key="cmirrord:1_stop_0">
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" daemon_timeout="60"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="58" operation="stop" operation_key="vg1:1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="16">
    <action_set>
      <pseudo_event id="58" operation="stop" operation_key="vg1:1_stop_0">
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" volgrpname="cluster-vg"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="60" operation="stop" operation_key="ocfs2-1:1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="17">
    <action_set>
      <pseudo_event id="60" operation="stop" operation_key="ocfs2-1:1_stop_0">
        <attributes CRM_meta_clone="1" CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1" device="/dev/cluster-vg/fs1" directory="/var/lib/xen/images" fstype="ocfs2" options="acl"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="23" operation="stop" operation_key="base-group:1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="18">
    <action_set>
      <pseudo_event id="33" operation="start" operation_key="base-clone_start_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
      <trigger>
        <pseudo_event id="35" operation="stop" operation_key="base-clone_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="36" operation="stopped" operation_key="base-clone_stopped_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="19" priority="1000000">
    <action_set>
      <pseudo_event id="34" operation="running" operation_key="base-clone_running_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="33" operation="start" operation_key="base-clone_start_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="20">
    <action_set>
      <pseudo_event id="35" operation="stop" operation_key="base-clone_stop_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="21" priority="1000000">
    <action_set>
      <pseudo_event id="36" operation="stopped" operation_key="base-clone_stopped_0">
        <attributes CRM_meta_clone_max="4" CRM_meta_clone_node_max="1" CRM_meta_globally_unique="false" CRM_meta_notify="false" CRM_meta_record_pending="false" CRM_meta_timeout="240000" crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="24" operation="stopped" operation_key="base-group:1_stopped_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="35" operation="stop" operation_key="base-clone_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="22">
    <action_set>
      <pseudo_event id="3" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <pseudo_event id="54" operation="stop" operation_key="dlm:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="55" operation="stop" operation_key="o2cb:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="56" operation="stop" operation_key="clvm:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="57" operation="stop" operation_key="cmirrord:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="58" operation="stop" operation_key="vg1:1_stop_0"/>
      </trigger>
      <trigger>
        <pseudo_event id="60" operation="stop" operation_key="ocfs2-1:1_stop_0"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="23">
    <action_set>
      <pseudo_event id="4" operation="probe_complete" operation_key="probe_complete">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="5" operation="probe_complete" operation_key="probe_complete" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="24" priority="1000000">
    <action_set>
      <rsc_op id="5" operation="probe_complete" operation_key="probe_complete" on_node="hex-9" on_node_uuid="hex-9">
        <attributes CRM_meta_op_no_wait="true" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="6" operation="monitor" operation_key="vg1:0_monitor_0" on_node="hex-9" on_node_uuid="hex-9"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

