<transition_graph cluster-delay="60s" stonith-timeout="60s" failed-stop-offset="INFINITY" failed-start-offset="INFINITY" batch-limit="30" transition_id="0">
  <synapse id="0">
    <action_set>
      <rsc_op id="1" operation="monitor" operation_key="dummy_monitor_10000" on_node="devnode1" on_node_uuid="9240e90e-ea73-4008-b439-21bdcedb564b">
        <primitive id="dummy" long-id="dummy" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_interval="10000" CRM_meta_name="monitor" CRM_meta_on_fail="restart" CRM_meta_timeout="60000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="7" operation="start" operation_key="dummy_start_0" on_node="devnode1" on_node_uuid="9240e90e-ea73-4008-b439-21bdcedb564b"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="1">
    <action_set>
      <rsc_op id="2" operation="stop" operation_key="dummy_stop_0" on_node="devnode1" on_node_uuid="9240e90e-ea73-4008-b439-21bdcedb564b">
        <primitive id="dummy" long-id="dummy" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs/>
  </synapse>
  <synapse id="2">
    <action_set>
      <rsc_op id="7" operation="start" operation_key="dummy_start_0" on_node="devnode1" on_node_uuid="9240e90e-ea73-4008-b439-21bdcedb564b">
        <primitive id="dummy" long-id="dummy" class="ocf" provider="heartbeat" type="Dummy"/>
        <attributes CRM_meta_timeout="20000" crm_feature_set="3.0.1"/>
      </rsc_op>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="2" operation="stop" operation_key="dummy_stop_0" on_node="devnode1" on_node_uuid="9240e90e-ea73-4008-b439-21bdcedb564b"/>
      </trigger>
    </inputs>
  </synapse>
  <synapse id="3">
    <action_set>
      <pseudo_event id="3" operation="all_stopped" operation_key="all_stopped">
        <attributes crm_feature_set="3.0.1"/>
      </pseudo_event>
    </action_set>
    <inputs>
      <trigger>
        <rsc_op id="2" operation="stop" operation_key="dummy_stop_0" on_node="devnode1" on_node_uuid="9240e90e-ea73-4008-b439-21bdcedb564b"/>
      </trigger>
    </inputs>
  </synapse>
</transition_graph>

